### PR TITLE
Fix empty eukulele channel & unzipped user provided assembly

### PR DESCRIPTION
**Pull request by erikrikarddaniel**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/metatdenovo/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/metatdenovo _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

We were using the wrong function to populate the Eukulele db channel. Working on this, I noticed it was difficult to continue supporting multiple databases at once, so this is now dropped.

In #276 a user reported that a user provided assembly was always unzipped even if not zipped, resulting in overwriting the file with an empty file. I fixed that by zipping the input if not already zipped.

_Note:_ the new template is not implemented yet and new features are waiting in `dev`, which is why this PR is against `master`.

### CODE REVIEW

**Review by danilodileo — APPROVED** [review]
LGTM

**Review by d4straub — COMMENTED** [review]
Changes look fine to me, except: The tests fail with `ERROR ~ No such file or directory: Can't find a matching module file for include: ../modules/nf-core/pigz/compress/main` and indeed, there seems to be no such folder `modules/nf-core/pigz`! But it was added to `modules.json`, I dont really understand how that happened. I think that needs fixing?

**Comment by erikrikarddaniel** [comment]
> Changes look fine to me, except: The tests fail with `ERROR ~ No such file or directory: Can't find a matching module file for include: ../modules/nf-core/pigz/compress/main` and indeed, there seems to be no such folder `modules/nf-core/pigz`! But it was added to `modules.json`, I dont really understand how that happened. I think that needs fixing?

Good spot. I just forgot to `git add`! (I should have seen this myself, but was so focused on my expectation that tests should fail...)

**Review by d4straub — APPROVED** [review]
LGTM!

**Pull request merged**
