### PR TITLE
Get githubactions to run

### PR DESCRIPTION
**Pull request by emnilsson**
A test to see if I can get github actions to run when doing pull requests to dev (not 100% they should be run then though). I changed the `ci.yml` to use `LNUc-EEMiS` instead of `nf-core` at one place and then added some tests to run under profiles, it's the first part that I think might influence github actions.
Also, fixed some trailing whitespaces that the github linting complained about.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/metatdenovo/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/metatdenovo _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by erikrikarddaniel — APPROVED** [review]
Fixed a couple of linting problems too it looks like! :+1: 
Now I see there are actually a couple of problems, one with linting and another with `test_transdecoder`. The latter looks weird, why is the Covid genome there?

**Comment by danilodileo** [comment]
> Fixed a couple of linting problems too it looks like! 👍
> Now I see there are actually a couple of problems, one with linting and another with `test_transdecoder`. The latter looks weird, why is the Covid genome there?

That was my fault, I changed it now with the right samplesheet.csv. 😅 I will send the PR after this one is merged!

**Comment by emnilsson** [comment]
> one with linting

I don't know how to handle that one actually, because it seems to compare `lib/NfcoreSchema.groovy` in the `dev`-branch with the one in the `template`-branch and that one is older...

**Comment by emnilsson** [comment]
I'll merge this in spite of the lint error, that should be resolved when nf-core releases the updated version of tools.

**Pull request merged**
