### PR TITLE
Fix kofamscan download output

### PR DESCRIPTION
**Pull request by danilodileo**
## PR checklist

I just changed the kofamscan_download module so now it will not stop (there was a mismatch between the output and the check in the code)

### CODE REVIEW

**Review by erikrikarddaniel — APPROVED** [review]
Good.

**Comment by danilodileo** [comment]
@erikrikarddaniel  do you know anything about the last check? it is not solved after two days now so there is something wrong I think.

**Comment by erikrikarddaniel** [comment]
> @erikrikarddaniel do you know anything about the last check? it is not solved after two days now so there is something wrong I think.

It's probably stuck. Happens every now and then. I think it's fine to bypass branch protection (haven't seen that before).

**Comment by danilodileo** [comment]
> > @erikrikarddaniel do you know anything about the last check? it is not solved after two days now so there is something wrong I think.
> 
> It's probably stuck. Happens every now and then. I think it's fine to bypass branch protection (haven't seen that before).

I can't merge it, the button is locked because it is waiting the last check

**Pull request merged**
